language: python
python:
  - 3.7
  - 3.6
  - 3.5
sudo: false
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  apt_packages:
    - pandoc
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.5
      env: GROUP=js
    - python: 3.6
      env: GROUP=docs
cache:
  pip: true
  directories:
    - node_modules # NPM packages
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 8
  - |
    if [[ $GROUP == python ]]; then
      pip install codecov
    elif [[ $GROUP == js ]]; then
      npm install -g codecov
    fi
install:
  - |
    if [[ $GROUP == python ]]; then
      pip install --upgrade ".[test]" -v
    elif [[ $GROUP == js ]]; then
      pip install --upgrade -e ".[test]" -v
    elif [[ $GROUP == docs ]]; then
      pip install --upgrade -e ".[test, examples, docs]" -v
    fi
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    if [[ $GROUP == js ]]; then
      export CHROME_BIN=google-chrome-stable
    fi
    git config --global user.email travis@fake.com
    git config --global user.name "Travis CI"
script:
  - |
    EXIT_STATUS=0
    if [[ $GROUP == python ]]; then
      pushd $(mktemp -d)
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=ipyscales --pyargs ipyscales || EXIT_STATUS=$?
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=ipyscales $TRAVIS_BUILD_DIR/examples || EXIT_STATUS=$?
      popd
    elif [[ $GROUP == js ]]; then
      pushd ts
      npm run test:ci || EXIT_STATUS=$?
      popd
    elif [[ $GROUP == docs ]]; then
      cd docs
      make html || EXIT_STATUS=$?
      make linkcheck || EXIT_STATUS=$?
      cd ..
      python -m pytest_check_links --links-ext=.md -o testpaths=. -o addopts= || EXIT_STATUS=$?
    fi
    (exit $EXIT_STATUS)
after_success:
  - codecov
